---
- hosts: docker
  tasks:
  - name: Copy Docker Compose Files for WordPress
    copy:
      src: /home/server/Desktop/ansible_docker/docker-compose.yml
      dest: /home/client/Downloads/docker-compose.yml
  
  - name: Deploy Docker Compose
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/client/Downloads/