---
- hosts: all
  become: yes
  tasks:
  - name: Create data container
    docker_container:
      name: 'pftp-data'
      image: busybox
      state: present
      volumes:
        - '/home/ftpusers/'
    when: True

  - name: "Setup ftp data folder"
    file:
      path: '/data/pftp'
      state: directory
      mode: 0777
    become: yes
    when: not True

  - name: "Pull Pure-FTPd image - stilliard/pure-ftpd:hardened"
    docker_image:
      name: 'stilliard/pure-ftpd'
      tag: 'hardened'
      source: pull

  - name: Setup Pure-FTPd container
    docker_container:
      name:  pftp
      image: stilliard/pure-ftpd:hardened
      state: started
      ports: "21:21,{% for port in range(30000, 30010) %}{{port}}:{{port}}{% if not loop.last %},{% endif %}{% endfor %}"
      volumes:
        - "/data/pftp:/home/ftpusers/"
      env:
        PUBLICHOST: 'localhost'
        ADDED_FLAGS: -d -d -O clf:/var/log/pureftpd.log --tls=0

      log_driver: 'json-file'
      log_options: '{}'

    register: pftp_container

  - name: Wait until Pure-FTPd is available
    wait_for: port=21 delay=3
    when: pftp_container.changed

  - name: Add service user
    include: add_user_play.yml
    vars:
      pftp_user:     "ftpadmin"
      pftp_password: "ftpadmin"